server:
local-zone: "addlive.io" always_null
local-zone: "ads-twitter.com" always_null
local-zone: "bsky.app" always_null
local-zone: "byteoversea.com" always_null
local-zone: "calibra.com" always_null
local-zone: "cdninstagram.com" always_null
local-zone: "facebook-hardware.com" always_null
local-zone: "facebook.com" always_null
local-zone: "facebook.me" always_null
local-zone: "facebook.net" always_null
local-zone: "facebookawards.com" always_null
local-zone: "fb.com" always_null
local-zone: "fb.me" always_null
local-zone: "fbcdn.com" always_null
local-zone: "fbcdn.net" always_null
local-zone: "fbsbx.com" always_null
local-zone: "feelinsonice.com" always_null
local-zone: "ig.me" always_null
local-zone: "instagr.am" always_null
local-zone: "instagram.com" always_null
local-zone: "instagram.net" always_null
local-zone: "like-video.com" always_null
local-zone: "like.video" always_null
local-zone: "likee.video" always_null
local-zone: "likeevideo.com" always_null
local-zone: "likeimo.tech" always_null
local-zone: "liketech.tech" always_null
local-zone: "m.me" always_null
local-zone: "messenger.com" always_null
local-zone: "meta.com" always_null
local-zone: "meta.me" always_null
local-zone: "misskey.io" always_null
local-zone: "oculus.com" always_null
local-zone: "oculusvr.com" always_null
local-zone: "periscope.tv" always_null
local-zone: "pscp.tv" always_null
local-zone: "sc-cdn.net" always_null
local-zone: "sc-corp.net" always_null
local-zone: "sc-gw.com" always_null
local-zone: "sc-jpl.com" always_null
local-zone: "sc-prod.net" always_null
local-zone: "sc-static.net" always_null
local-zone: "snap-dev.net" always_null
local-zone: "snap-storage-cdn.l.google.com" always_null
local-zone: "snapads.com" always_null
local-zone: "snapchat.com" always_null
local-zone: "snapkit.com" always_null
local-zone: "snapmap.com" always_null
local-zone: "snapmap.org" always_null
local-zone: "snapmaps.com" always_null
local-zone: "snssdk.com" always_null
local-zone: "t.co" always_null
local-zone: "tfbnw.net" always_null
local-zone: "threads.com" always_null
local-zone: "tiktok.com" always_null
local-zone: "tiktok.org" always_null
local-zone: "tiktokcdn.com" always_null
local-zone: "tiktokv.com" always_null
local-zone: "tweetdeck.com" always_null
local-zone: "twimg.com" always_null
local-zone: "twitpic.com" always_null
local-zone: "twitter.co" always_null
local-zone: "twitter.com" always_null
local-zone: "twitterinc.com" always_null
local-zone: "twitteroauth.com" always_null
local-zone: "twitterstat.us" always_null
local-zone: "twtrdns.net" always_null
local-zone: "twttr.com" always_null
local-zone: "userapi.com" always_null
local-zone: "vk-cdn.net" always_null
local-zone: "vk-portal.net" always_null
local-zone: "vk.com" always_null
local-zone: "vk.company" always_null
local-zone: "vk.ru" always_null
local-zone: "vkontakte.ru" always_null
local-zone: "vkuser.net" always_null
local-zone: "vkuseraudio.net" always_null
local-zone: "vkuservideo.net" always_null
local-zone: "x.com" always_null
